apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod6
  name: ashupod6
spec:
  containers:
  - image: dockerashu/oracle:may2020
    name: ashupod6
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
