apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: likipod7
  name: likipod7
spec:
  containers:
  - image: dockerashu/oracle:may2020
    name: likipod7
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: likiv6
  name: likiv6
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: likiv6
status:
  loadBalancer: {}
