apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: likipod2
  name: likipod2
spec:
  containers:
  - image: nginx
    name: likipod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
