apiVersion: v1
kind: ReplicationController
metadata:
 name: likirc
 labels:
  x: helloliki

spec:
 replicas: 2
 template:
  metadata:
   name: mypod
   labels:
    x: helloliki
  spec:
   containers:
    - name: liki
      image: nginx
      ports:
       - containerPort: 80
