apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: likidep1
  name: likidep1
  namespace: likins
spec:
  replicas: 5
  selector:
    matchLabels:
      app: likidep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: likidep1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
