apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: likdep
  name: likdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: likdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: likdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
